name: Porduction Grade CI For ReactApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  SONAR_TOKEN_git: ${{secrets.SONAR_TOKEN}}
  SONAR_HOST_URL_git: ${{secrets.SONAR_HOST_URL}}




jobs:
  Code_Check:
    
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22

      - name: Trivy Fs
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: "./"
          output: 'trivy-results.sarif'

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        with: 
          fetch-depth: 0

      - name: Lint Check
        run: |
          npm run lint:fix
          npm run lint || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        with:
          projectBaseDir: .
          args: |
              -Dsonar.projectKey=WebApp
              -Dsonar.sources=.
        env:
          SONAR_TOKEN: $SONAR_TOKEN
          SONAR_HOST_URL: $SONAR_HOST_URL

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: $SONAR_TOKEN
          SONAR_HOST_URL: $SONAR_HOST_URL

            






      
          
    

    
